# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "956eb85ae1f2605b7019c0bbab4e9f64"
application_url = "https://awarded-sol-moscow-spider.trycloudflare.com"
embedded = true
name = "Delivery Date Config - Remix"
handle = "delivery-date-config-remix"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://awarded-sol-moscow-spider.trycloudflare.com/auth/callback",
  "https://awarded-sol-moscow-spider.trycloudflare.com/auth/shopify/callback",
  "https://awarded-sol-moscow-spider.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "arctic-grey-assessment.myshopify.com"
automatically_update_urls_on_dev = true
