api_version = "2024-10"

[[extensions]]
name = "Delivery Date Picker"
handle = "delivery-date-picker"
type = "ui_extension"


[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true
block_progress = true
